# N3 Vibecode Gallery
org.gradle.jvmargs=-Xmx1400m -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.compiler.execution.strategy=in-process
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableResourceOptimizations=true

org.gradle.workers.max=1
